### ISSUE TITLE
Library doesn't build with latest mos tool

### ISSUE THREAD

**Issue by Wolf4992** [tripflex/wifi-captive-portal#12]
I'm not not sure why, but I haven't been able to build projects that include this library with the latest mos tool (2.10.2).

My mos.yml file is setup as follows and builds properly when I exclude the library:
```
author: mongoose-os
description: A JS-enabled demo Mongoose OS firmware
arch: esp32
version: 1.0
manifest_version: 2017-05-18
libs_version: ${mos.version}
modules_version: ${mos.version}
mongoose_os_version: ${mos.version}

config_schema:
  - ["mqtt.server", "iot.eclipse.org:1883"]
  - ["i2c.enable", true]

tags:
  - js

filesystem:
  - fs

libs:
  - origin: https://github.com/mongoose-os-libs/boards
  - origin: https://github.com/mongoose-os-libs/js-demo-bundle
  - origin: https://github.com/tripflex/wifi-captive-portal/
```

I am getting the following errors:

```
volumes/2.10.2/apps/app1/esp32/build_contexts/build_ctx_165963155/build/objs/mosapp/libmosapp.a(mgos_deps_init.o):(.rodata.descrs+0x74): undefined reference to `mgos__init'
collect2: error: ld returned 1 exit status
make: *** [/fwbuild-volumes/2.10.2/apps/app1/esp32/build_contexts/build_ctx_165963155/build/objs/app1.elf] Error 1
/opt/Espressif/esp-idf/make/project.mk:435: recipe for target '/fwbuild-volumes/2.10.2/apps/app1/esp32/build_contexts/build_ctx_165963155/build/objs/app1.elf' failed
make: Leaving directory '/app'
Error: exit status 2
/go/src/cesanta.com/mos/build_local.go:648: 
/go/src/cesanta.com/mos/build_local.go:635: 
/go/src/cesanta.com/mos/build_local.go:396: 
/go/src/cesanta.com/mos/build.go:203: 
/go/src/cesanta.com/mos/build.go:146: 
/go/src/cesanta.com/mos/main.go:176: build failed
Error: /go/src/cesanta.com/mos/build_remote.go:281: build failed
/go/src/cesanta.com/mos/build.go:203: 
/go/src/cesanta.com/mos/build.go:146: 
/go/src/cesanta.com/mos/main.go:176: build failed
```
The full log is attached below. Any help resolving this issue would be much appreciated.

[log.txt](https://github.com/tripflex/wifi-captive-portal/files/2766054/log.txt)
